#!/usr/bin/env bash

# List from "The Moz Top 500 Websites"
# https://moz.com/top500
go run github.com/h-matsuo/gopl/ch01/ex10 \
  https://youtube.com \
  https://www.google.com \
  https://apple.com \
  https://play.google.com \
  https://support.google.com \
  https://www.blogger.com \
  https://microsoft.com \
  https://docs.google.com \
  https://maps.google.com \
  https://linkedin.com \
  https://en.wikipedia.org \
  https://cloudflare.com \
  https://plus.google.com \
  https://wordpress.org \
  https://adobe.com \
  https://drive.google.com \
  https://googleusercontent.com \
  https://accounts.google.com \
  https://youtu.be \
  https://mozilla.org \
  https://vimeo.com \
  https://europa.eu \
  https://sites.google.com \
  https://bp.blogspot.com \
  https://bbc.co.uk \
  https://istockphoto.com \
  https://github.com \
  https://amazon.com \
  https://vk.com \
  https://creativecommons.org \
  https://facebook.com \
  https://medium.com \
  https://es.wikipedia.org \
  https://line.me \
  https://uol.com.br \
  https://pt.wikipedia.org \
  https://forbes.com \
  https://msn.com \
  https://dropbox.com \
  https://google.es \
  https://imdb.com \
  https://developers.google.com \
  https://mail.ru \
  https://feedburner.com \
  https://google.com.br \
  https://google.co.uk \
  https://bbc.com \
  https://cnn.com \
  https://theguardian.com \
  https://w3.org \
  https://reuters.com \
  https://mail.google.com \
  https://news.google.com \
  https://paypal.com \
  https://nytimes.com \
  https://policies.google.com \
  https://www.yahoo.com \
  https://myspace.com \
  https://fr.wikipedia.org \
  https://aliexpress.com \
  https://who.int \
  https://dailymotion.com \
  https://google.fr \
  https://wikimedia.org \
  https://get.google.com \
  https://jimdofree.com \
  https://photos.google.com \
  https://google.de \
  https://globo.com \
  https://slideshare.net \
  https://gstatic.com \
  https://t.me \
  https://buydomains.com \
  https://nih.gov \
  https://hugedomains.com \
  https://whatsapp.com \
  https://live.com \
  https://google.co.jp \
  https://picasa.google.com \
  https://lefigaro.fr \
  https://themeforest.net \
  https://cpanel.com \
  https://cpanel.net \
  https://picasaweb.google.com \
  https://ft.com \
  https://marketingplatform.google.com \
  https://id.wikipedia.org \
  https://amazon.co.jp \
  https://usatoday.com \
  https://archive.org \
  https://scribd.com \
  https://rt.com \
  https://huffingtonpost.com \
  https://mirror.co.uk \
  https://washingtonpost.com \
  https://www.gov.uk \
  https://files.wordpress.com \
  https://mediafire.com \
  https://networkadvertising.org \
  https://cdc.gov \
  https://gravatar.com \
  https://samsung.com \
  https://code.google.com \
  https://webmd.com \
  https://myaccount.google.com \
  https://dailymail.co.uk \
  https://www.wix.com \
  https://terra.com.br \
  https://independent.co.uk \
  https://privacyshield.gov \
  https://translate.google.com \
  https://thesun.co.uk \
  https://twitter.com \
  https://books.google.com \
  https://google.it \
  https://abril.com.br \
  https://android.com \
  https://office.com \
  https://ipv4.google.com \
  https://harvard.edu \
  https://search.google.com \
  https://hatena.ne.jp \
  https://fandom.com \
  https://opera.com \
  https://sedo.com \
  https://plesk.com \
  https://goo.gl \
  https://telegraph.co.uk \
  https://pinterest.com \
  https://change.org \
  https://ig.com.br \
  https://issuu.com \
  https://youronlinechoices.com \
  https://telegram.me \
  https://draft.blogger.com \
  https://bing.com \
  https://un.org \
  https://rakuten.co.jp \
  https://wsj.com \
  https://tools.google.com \
  https://businessinsider.com \
  https://namecheap.com \
  https://de.wikipedia.org \
  https://news.yahoo.com \
  https://bit.ly \
  https://bloomberg.com \
  https://ok.ru \
  https://wikia.com \
  https://dan.com \
  https://cnet.com \
  https://booking.com \
  https://elpais.com \
  https://amazon.co.uk \
  https://amazon.de \
  https://steampowered.com \
  https://wired.com \
  https://fb.com \
  https://abcnews.go.com \
  https://time.com \
  https://aol.com \
  https://aboutads.info \
  https://tinyurl.com \
  https://nasa.gov \
  https://ebay.com \
  https://google.ru \
  https://foxnews.com \
  https://pixabay.com \
  https://amazon.es \
  https://wikihow.com \
  https://washington.edu \
  https://stanford.edu \
  https://www.livejournal.com \
  https://google.ca \
  https://rambler.ru \
  https://ietf.org \
  https://smh.com.au \
  https://twitch.tv \
  https://hp.com \
  https://secureserver.net \
  https://ibm.com \
  https://newsweek.com \
  https://ovh.net \
  https://economist.com \
  https://mystrikingly.com \
  https://adssettings.google.com \
  https://engadget.com \
  https://hm.com \
  https://sciencedirect.com \
  https://forms.gle \
  https://enable-javascript.com \
  https://netvibes.com \
  https://t.co \
  https://mit.edu \
  https://lemonde.fr \
  https://latimes.com \
  https://addthis.com \
  https://oup.com \
  https://yadi.sk \
  https://it.wikipedia.org \
  https://www.over-blog.com \
  https://imageshack.us \
  https://instructables.com \
  https://nokia.com \
  https://target.com \
  https://techcrunch.com \
  https://groups.google.com \
  https://e-recht24.de \
  https://nhk.or.jp \
  https://ovh.com \
  https://berkeley.edu \
  https://shopify.com \
  https://google.co.id \
  https://naver.com \
  https://news.com.au \
  https://playstation.com \
  https://www.weebly.com \
  https://mashable.com \
  https://sfgate.com \
  https://buzzfeed.com \
  https://academia.edu \
  https://ted.com \
  https://britannica.com \
  https://doubleclick.net \
  https://yahoo.co.jp \
  https://disqus.com \
  https://list-manage.com \
  https://eventbrite.com \
  https://google.com.tw \
  https://ru.wikipedia.org \
  https://nginx.org \
  https://www.wikipedia.org \
  https://espn.com \
  https://mysql.com \
  https://scoop.it \
  https://loc.gov \
  https://nationalgeographic.com \
  https://trustpilot.com \
  https://asus.com \
  https://instagram.com \
  https://php.net \
  https://surveymonkey.com \
  https://over-blog-kiwi.com \
  https://biglobe.ne.jp \
  https://000webhost.com \
  https://disney.com \
  https://researchgate.net \
  https://channel4.com \
  https://guardian.co.uk \
  https://elmundo.es \
  https://lg.com \
  https://ria.ru \
  https://akamaihd.net \
  https://hollywoodreporter.com \
  https://goo.ne.jp \
  https://gnu.org \
  https://cbsnews.com \
  https://finance.yahoo.com \
  https://whitehouse.gov \
  https://ovh.co.uk \
  https://shutterstock.com \
  https://storage.googleapis.com \
  https://npr.org \
  https://netflix.com \
  https://apache.org \
  https://vice.com \
  https://fastcompany.com \
  https://yelp.com \
  https://welt.de \
  https://sapo.pt \
  https://stackoverflow.com \
  https://abc.es \
  https://kickstarter.com \
  https://ytimg.com \
  https://amazon.fr \
  https://orkut.com.br \
  https://imageshack.com \
  https://naver.jp \
  https://detik.com \
  https://gofundme.com \
  https://cornell.edu \
  https://rapidshare.com \
  https://columbia.edu \
  https://cisco.com \
  https://windowsphone.com \
  https://metro.co.uk \
  https://4shared.com \
  https://nydailynews.com \
  https://usnews.com \
  https://google.co.in \
  https://bp2.blogger.com \
  https://psychologytoday.com \
  https://noaa.gov \
  https://abc.net.au \
  https://wiley.com \
  https://tes.com \
  https://nikkei.com \
  https://princeton.edu \
  https://thetimes.co.uk \
  https://google.nl \
  https://pl.wikipedia.org \
  https://ja.wikipedia.org \
  https://nvidia.com \
  https://ign.com \
  https://express.co.uk \
  https://gmail.com \
  https://wa.me \
  https://my.yahoo.com \
  https://mozilla.com \
  https://walmart.com \
  https://marriott.com \
  https://indiatimes.com \
  https://ox.ac.uk \
  https://nature.com \
  https://urbandictionary.com \
  https://spiegel.de \
  https://iubenda.com \
  https://cambridge.org \
  https://nypost.com \
  https://vox.com \
  https://cnbc.com \
  https://bloglovin.com \
  https://tripadvisor.com \
  https://oracle.com \
  https://ea.com \
  https://ikea.com \
  https://nginx.com \
  https://godaddy.com \
  https://weibo.com \
  https://mega.nz \
  https://qq.com \
  https://gizmodo.com \
  https://wp.com \
  https://standard.co.uk \
  https://bp0.blogger.com \
  https://cbc.ca \
  https://quora.com \
  https://spotify.com \
  https://huffpost.com \
  https://bt.com \
  https://photobucket.com \
  https://sendspace.com \
  https://box.com \
  https://digg.com \
  https://xbox.com \
  https://alibaba.com \
  https://unesco.org \
  https://addtoany.com \
  https://dell.com \
  https://icann.org \
  https://pexels.com \
  https://deezer.com \
  https://fifa.com \
  https://ziddu.com \
  https://dw.com \
  https://goodreads.com \
  https://zendesk.com \
  https://worldbank.org \
  https://utexas.edu \
  https://a8.net \
  https://amazon.it \
  https://yandex.ru \
  https://umich.edu \
  https://bitly.com \
  https://theatlantic.com \
  https://pbs.org \
  https://bp1.blogger.com \
  https://theverge.com \
  https://about.com \
  https://sciencemag.org \
  https://depositfiles.com \
  https://soundcloud.com \
  https://google.pl \
  https://ggpht.com \
  https://sciencedaily.com \
  https://nbcnews.com \
  https://blackberry.com \
  https://bandcamp.com \
  https://yale.edu \
  https://variety.com \
  https://m.wikipedia.org \
  https://sputniknews.com \
  https://googleblog.com \
  https://elsevier.com \
  https://steamcommunity.com \
  https://about.me \
  https://gesetze-im-internet.de \
  https://thestar.com \
  https://sakura.ne.jp \
  https://adweek.com \
  https://amzn.to \
  https://sports.yahoo.com \
  https://chicagotribune.com \
  https://discovery.com \
  https://fda.gov \
  https://slate.com \
  https://dreniq.com \
  https://example.com \
  https://so-net.ne.jp \
  https://mayoclinic.org \
  https://nba.com \
  https://oreilly.com \
  https://ehow.com \
  https://coursera.org \
  https://photos1.blogger.com \
  https://arxiv.org \
  https://zeit.de \
  https://snapchat.com \
  https://offset.com \
  https://interia.pl \
  https://thoughtco.com \
  https://pinterest.co.uk \
  https://eonline.com \
  https://thehill.com \
  https://imgur.com \
  https://unicef.org \
  https://state.gov \
  https://nps.gov \
  https://rediff.com \
  https://corriere.it \
  https://autodesk.com \
  https://home.pl \
  https://businesswire.com \
  https://biblegateway.com \
  https://axs.com \
  https://scientificamerican.com \
  https://asahi.com \
  https://psu.edu \
  https://ssl-images-amazon.com \
  https://thefreedictionary.com \
  https://geocities.jp \
  https://sina.com.cn \
  https://ebay.co.uk \
  https://outlook.com \
  https://usc.edu \
  https://huawei.com \
  https://usgs.gov \
  https://people.com \
  https://stores.jp \
  https://vchecks.me \
  https://amazon.ca \
  https://parallels.com \
  https://repubblica.it \
  https://google.com.au \
  https://billboard.com \
  https://airbnb.com \
  https://last.fm \
  https://gutenberg.org \
  https://video.google.com \
  https://xinhuanet.com \
  https://cocolog-nifty.com \
  https://si.edu \
  https://ubuntu.com \
  https://venturebeat.com \
  https://entrepreneur.com \
  https://espn.go.com \
  https://weforum.org \
  https://nifty.com \
  https://pastebin.com \
  https://house.gov \
  https://feedproxy.google.com \
  https://boston.com \
  https://dictionary.com \
  https://arstechnica.com \
  https://khanacademy.org \
  https://ca.gov \
  https://etsy.com \
  https://canva.com \
  https://ap.org \
  https://ucoz.ru \
  https://indiegogo.com \
  https://daum.net \
  https://salon.com \
  https://softonic.com \
  https://megaupload.com \
  https://narod.ru \
  https://liveinternet.ru \
  https://cia.gov \
  https://ameblo.jp \
  https://lego.com \
  https://nicovideo.jp \
  https://medicalnewstoday.com \
  https://bp3.blogger.com \
  https://calendar.google.com \
  https://consumerreports.org \
  https://www.canalblog.com \
  https://fb.me \
  https://statista.com \
  https://lycos.com \
  https://answers.yahoo.com \
  https://behance.net \
  https://irs.gov \
  https://afternic.com \
  https://digitaltrends.com \
  https://politico.com \
  https://epa.gov \
  https://evernote.com \
  https://20minutos.es \
  https://ndtv.com \
  https://ftc.gov \
  https://lonelyplanet.com
